package XtraØkter.Uke4;

public enum BibliotekBestand {
    HUCKLEBERRY_FINN, MOMO, UENDELIGE_HISTORIE,
    RINGENES_HERRE, PROSSESSEN, HOBBITEN, KARDEMOMMEBY,
    KARIUS_OG_BAKTUS, FOUNDATION, DRØMMER_ROBOTER_OM_ELEKTRISKE_SAU,
    UT_PÅ_TUR, ET_DUKKEHJEM, BERLINERPOPLENE, VARG_VEUM_7
}
