package XtraØkter.Uke4;

public enum BibliotekBestand {
    BERLINERPOPLENE, DRØMMER_ROBOTER_OM_ELEKTRISKE_SAU, ET_DUKKEHJEM,
    FOUNDATION, HOBBITEN, HUCKLEBERRY_FINN, KARDEMOMMEBY,
    KARIUS_OG_BAKTUS, MOMO, PROSSESSEN,
    RINGENES_HERRE, UENDELIGE_HISTORIE, UT_PÅ_TUR, VARG_VEUM_7

}
